# docker-compose.yml

# Met docker-compose kun je eenvoudig je PostgreSQL database opstarten.
# De Go app zelf kan dan lokaal draaien (go run main.go), terwijl de DB in een container draait.
# Pas de DB credentials en host in de .env en config.go aan zodat ze overeenkomen.

version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
