services:
  - type: web
    name: gobackend
    env: docker
    buildCommand: docker build -t gobackend .
    startCommand: docker run -p $PORT:8080 gobackend
    envVars:
      # Database configuratie wordt automatisch ingesteld door Render
      - key: DB_HOST
        fromDatabase:
          name: DKL2025
          property: host
      - key: DB_NAME
        fromDatabase:
          name: DKL2025
          property: database
      - key: DB_USER
        fromDatabase:
          name: DKL2025
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: DKL2025
          property: password
      - key: DB_PORT
        fromDatabase:
          name: DKL2025
          property: port

databases:
  - name: DKL2025
    databaseName: dekoninklijkeloop2025
    plan: free